[Probability and Statistics for Data Science](https://www.ps4ds.net/) 

Code for Exercise 11.13

Topic modeling via low-rank modeling for a small made-up dataset\
Topics: Low-rank model, singular value decomposition, nonnegative matrix factorization 

Author: Carlos Fernandez-Granda

In [1]:
import numpy as np
from sklearn.decomposition import NMF

topics = ["singer", "exports", "congress", "elections", "candidate", "stock", 
          "concert", "market", "band"]
X = np.array([[6,1,1,0,0,1,9,0,8], [1,0,9,5,8,1,0,1,0], [8,1,0,1,0,0,9,1,7],
              [0,7,1,0,0,9,1,7,0], [0,5,6,7,5,6,0,7,2], [1,0,8,5,9,2,0,0,1]])
model = NMF(n_components=3, init='random', random_state=0)
model.fit(X) 
W = model.fit_transform(X);
H = model.components_;

U, s, V = np.linalg.svd(X, full_matrices=False)
print("U")
print( np.round(U[:,:3].T,3))
print( "V")
print( np.round(V[:3,:],3))
print( "s")
print( np.round(s,3))

print("rank 3")
L3 = np.dot(U[:,:3], np.dot(np.diag(s[:3]),V[:3,:])) 
np.set_printoptions(precision=3)
print(L3)
print( "W")
print( W.T)
print( "H")
print( H)
WH = np.dot(W,H)
print( "WH")
print(WH )
print("SVD error: " + str(np.round(np.linalg.norm(X[:]-L3[:]),2)))
print("NMF error: " + str(np.round(np.linalg.norm(X[:]-WH[:]),2)))

U
[[ 0.244  0.465  0.243  0.317  0.583  0.474]
 [ 0.645 -0.233  0.673 -0.028 -0.179 -0.209]
 [ 0.076  0.391  0.08  -0.772 -0.282  0.399]]
V
[[ 0.184  0.238  0.509  0.382  0.461  0.339  0.199  0.296  0.224]
 [ 0.468  0.012 -0.225 -0.148 -0.247 -0.071  0.629 -0.053  0.494]
 [ 0.133 -0.468  0.304  0.144  0.373 -0.518  0.044 -0.485  0.07 ]]
s
[23.642 18.825 14.232  3.63   2.026  1.365]
rank 3
[[ 6.885e+00  1.016e+00  5.364e-01  5.558e-01  6.722e-02  5.387e-01
   8.825e+00  5.383e-01  7.366e+00]
 [ 7.035e-01 -4.418e-02  8.278e+00  5.652e+00  8.233e+00  1.150e+00
  -3.288e-01  7.923e-01  6.827e-01]
 [ 7.140e+00  9.840e-01  4.236e-01  4.763e-01 -5.140e-02  4.564e-01
   9.159e+00  4.686e-01  7.630e+00]
 [-3.229e-01  6.919e+00  5.961e-01  1.348e+00 -5.137e-01  8.274e+00
   6.744e-01  7.584e+00  6.459e-01]
 [ 4.241e-01  5.110e+00  6.554e+00  5.175e+00  5.689e+00  6.982e+00
   4.421e-01  6.208e+00  1.136e+00]
 [ 9.708e-01 -3.668e-02  8.319e+00  5.683e+00  8.261e+00  1.136e+00
   5.388e-03  7.808e