[Probability and Statistics for Data Science](https://www.ps4ds.net/) 

Code for Exercise 5.14

Topics: Gaussian random vectors

Author: Carlos Fernandez-Granda

In [1]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=2,suppress=True)
import numpy.linalg as linalg

In [2]:
data = np.array([
    [1.5,2.3,0.8,1.2,2.0,1.2,0.7,2.7,2.3,0.6],
    [20,15,18,19,17,22,21,14,17,22],
    [8,12,6,10,17,12,9,14,10,8],
    [110,94,152,123,78,60,111,83,85,90],
    [12,21,9,14,19,15,7,29,22,15]
])

mu = np.mean(data,axis=1)
print("Mean",mu)

Sigma = np.cov(data,bias=True)
print("Covariance matrix parameter",Sigma)

Mean [ 1.53 18.5  10.6  98.6  16.3 ]
Covariance matrix parameter [[  0.51  -1.61   1.45  -7.89   3.97]
 [ -1.61   7.05  -3.9    0.6  -12.25]
 [  1.45  -3.9    9.44 -52.46  12.62]
 [ -7.89   0.6  -52.46 616.84 -90.18]
 [  3.97 -12.25  12.62 -90.18  39.01]]


In [3]:
mu_fruit = mu[0]
mu_rest = mu[1:]
Sigma_fruit = Sigma[0,0]
Sigma_rest = Sigma[1:,1:]
Sigma_fruit_rest = Sigma[1:,0]

rest = np.array([15,20,120,8])

mu_cond = mu_fruit + Sigma_fruit_rest.T @ linalg.inv(Sigma_rest) @ (rest - mu_rest)
Sigma_cond = Sigma_fruit - Sigma_fruit_rest.T @ linalg.inv(Sigma_rest) @ Sigma_fruit_rest

print(mu_cond)
print(Sigma_cond)

1.7654015973964683
0.03747546420415904
